PopularGroupsApp/Controllers/BandController.cs
using PopularGroupsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PopularGroupsApp.Controllers
{
    public class BandController : Controller
    {
        // GET: Band
        public ActionResult Index()
        {
            var bands = Band.bandsCreate();
            var concerts = Concert.concertCreate();

            foreach (var band in bands)
            {
                band.concerts = concerts.Where(c => c.BandId == band.Id).ToList();
            }

            @TempData["Tittle"] = "Próximos conciertos";

            var orderedBands = bands.OrderBy(b => b.Style).ToList();

            return View(orderedBands);
        }


        public PartialViewResult ConcertBands(int id)
        {
            var band = Band.bandsCreate().FirstOrDefault(b => b.Id == id);
            return PartialView("ConcertBands", band);
        }






    }
}

PopularGroupsApp/Controllers/HomeController.cs
using PopularGroupsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PopularGroupsApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            

            TempData["Tittle"] = "Listado de bandas";

            var bandStyle = Band.bandsCreate().OrderBy(o => o.Style).ToList();

            

            return View(bandStyle);
        }

        public ActionResult Details( int id) 
        {
            var bands = Band.bandsCreate().FirstOrDefault(p => p.Id == id);
            var concert = Concert.concertCreate().Where(w => w.BandId == id).ToList();



        ViewBag.Concert = concert;
            TempData["Tittle"] = "Detalles de la banda";


            return View(bands);
        }

        
    }
}

PopularGroupsApp/Views/Home/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.GlobalText = "Detalles";
    ViewBag.Footer = "Todos los derechos reservados";
}

<div class="container my-4 d-flex justify-content-center">
    <div class="border border-warning p-4" style="background-color: transparent; width: 80%;">
        <div class="row justify-content-center">
            <!-- Banda -->
            <div class="col-md-8 text-center mb-4">
                <h4 class="text-warning">@Model.Name</h4>
                <img src="@Url.Content(Model.ImagePath)" alt="@Model.Name" class="img-fluid mb-3" style="width:200px;height:auto;" />
                <h4 class="text-warning">@Model.Style</h4>
                <h5 class="text-warning">Ciudad de origen (@Model.Cities)</h5>
                <p class="text-light" style="font-size: 1.1rem;">@Model.Description</p>

               
            </div>

            <!-- Conciertos -->
            <div class="col-md-8">
                @if (ViewBag.Concert is List<PopularGroupsApp.Models.Concert> concerts && concerts.Any())
                {
                    <h5 class="text-warning mb-3">Próximos Conciertos</h5>
                    <table class="table table-dark table-striped table-bordered w-100">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ciudad</th>
                                <th>Fecha</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var concert in concerts)
                            {
                                <tr>
                                    <td>@concert.Name</td>
                                    <td>@concert.City</td>
                                    <td>@concert.Date.ToShortDateString()</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p class="text-light">No hay conciertos disponibles.</p>
                }
            </div>
        </div>
        <!-- Botón volver -->
        <div class="text-center mt-4">
            <a href="@Url.Action("Index", "Home")" class="btn btn-outline-warning mx-2 px-4">Inicio</a>
            <a href="@Url.Action("Index", "Band")" class="btn btn-outline-warning mx-2 px-4">Eventos</a>
        </div>
    </div>


</div>

PopularGroupsApp/Views/Home/Index.cshtml
@using PopularGroupsApp.Models
@model List<Band>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.GlobalText = "Listado de bandas";
    ViewBag.Footer = "Todos los derechos reservados";
}



<div class="container-fluid d-flex align-items-center justify-content-center" style="min-height:100vh;">
    <div class="row g-4 justify-content-center">
        @foreach (var band in Model)
        {
            <div class="col-md-6 col-lg-2 d-flex justify-content-center">
                <div class="card shadow-sm" style="max-width:18rem;">
                    <div class="card-header bg-dark text-white text-center">
                        <h5 class="mb-0 text-warning">@band.Style</h5>
                    </div>
                    
                    <div class="card-body text-center bg-dark">
                        <a href="@Url.Action("Details", new { id = band.Id })">
                            <img src="@Url.Content(band.ImagePath)" alt="@band.Name" class="img-fluid" style="width:200px;height:auto;" />
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>



<div class="d-flex justify-content-center my-4">
    @Html.ActionLink("Conciertos", "Index", "Band", null, new { @class = "btn btn-outline-warning" })
</div>